[package]
name = "emulator_6502"
version = "0.1.0"
authors = ["Richard Bickford <rzacharski05@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
sdl2 = "0.34.0"