use AddressingMode::{
    Absolute, AbsoluteIndirect, AbsoluteXIndex, AbsoluteYIndex, Accumulator, Immediate, Implied,
    Relative, ZeroPage, ZeroPageXIndex, ZeroPageXIndexIndirect, ZeroPageYIndex,
    ZeroPageYIndexIndirect,
};

use crate::cpu::addressing_mode::AddressingMode;
use crate::cpu::registers::Registers;
use crate::memory::Memory;

pub struct Operation {
    opcode: u8,
    instruction_shorthand: String,
    pub addressing_mode: AddressingMode,
}

impl Operation {
    pub fn next(registers: &mut Registers, memory: &mut Memory) -> Operation {
        let opcode = memory.read_byte(registers.program_counter);

        let (addressing_mode, instruction_shorthand) =
            resolve_opcode(opcode, registers.program_counter);

        let instruction_shorthand = instruction_shorthand.to_string();

        Operation {
            opcode,
            instruction_shorthand,
            addressing_mode,
        }
    }
}

// EXHAUSTIVE list of opcodes
fn resolve_opcode(opcode: u8, address: usize) -> (AddressingMode, &'static str) {
    match opcode {
        0x00 => (Implied, "BRK"),
        0x01 => (ZeroPageXIndexIndirect(address), "ORA"),
        0x02 => (Implied, "JAM"),
        0x03 => (ZeroPageXIndexIndirect(address), "SLO"),
        0x04 => (ZeroPage(address), "NOP"),
        0x05 => (ZeroPage(address), "ORA"),
        0x06 => (ZeroPage(address), "ASL"),
        0x07 => (ZeroPage(address), "SLO"),
        0x08 => (Implied, "PHP"),
        0x09 => (Immediate(address), "ORA"),
        0x0A => (Accumulator, "ASL"),
        0x0B => (Immediate(address), "ANC"),
        0x0C => (Absolute(address), "NOP"),
        0x0D => (Absolute(address), "ORA"),
        0x0E => (Absolute(address), "ASL"),
        0x0F => (Absolute(address), "SLO"),
        0x10 => (Relative(address), "BPL"),
        0x11 => (ZeroPageYIndexIndirect(address), "ORA"),
        0x12 => (Implied, "JAM"),
        0x13 => (ZeroPageYIndexIndirect(address), "SLO"),
        0x14 => (ZeroPageXIndex(address), "NOP"),
        0x15 => (ZeroPageXIndex(address), "ORA"),
        0x16 => (ZeroPageXIndex(address), "ASL"),
        0x17 => (ZeroPageXIndex(address), "SLO"),
        0x18 => (Implied, "CLC"),
        0x19 => (AbsoluteYIndex(address), "ORA"),
        0x1A => (Implied, "NOP"),
        0x1B => (AbsoluteYIndex(address), "SLO"),
        0x1C => (AbsoluteXIndex(address), "NOP"),
        0x1D => (AbsoluteXIndex(address), "ORA"),
        0x1E => (AbsoluteXIndex(address), "ASL"),
        0x1F => (AbsoluteXIndex(address), "SLO"),
        0x20 => (Absolute(address), "JSR"),
        0x21 => (ZeroPageXIndexIndirect(address), "AND"),
        0x22 => (Implied, "JAM"),
        0x23 => (ZeroPageXIndexIndirect(address), "RLA"),
        0x24 => (ZeroPage(address), "BIT"),
        0x25 => (ZeroPage(address), "AND"),
        0x26 => (ZeroPage(address), "ROL"),
        0x27 => (ZeroPage(address), "RLA"),
        0x28 => (Implied, "PLP"),
        0x29 => (Immediate(address), "AND"),
        0x2A => (Accumulator, "ROL"),
        0x2B => (Immediate(address), "ANC"),
        0x2C => (Absolute(address), "BIT"),
        0x2D => (Absolute(address), "AND"),
        0x2E => (Absolute(address), "ROL"),
        0x2F => (Absolute(address), "RLA"),
        0x30 => (Relative(address), "BMI"),
        0x31 => (ZeroPageYIndexIndirect(address), "AND"),
        0x32 => (Implied, "JAM"),
        0x33 => (ZeroPageYIndexIndirect(address), "RLA"),
        0x34 => (ZeroPageXIndex(address), "NOP"),
        0x35 => (ZeroPageXIndex(address), "AND"),
        0x36 => (ZeroPageXIndex(address), "ROL"),
        0x37 => (ZeroPageXIndex(address), "RLA"),
        0x38 => (Implied, "SEC"),
        0x39 => (AbsoluteYIndex(address), "AND"),
        0x3A => (Implied, "NOP"),
        0x3B => (AbsoluteYIndex(address), "RLA"),
        0x3C => (AbsoluteXIndex(address), "NOP"),
        0x3D => (AbsoluteXIndex(address), "AND"),
        0x3E => (AbsoluteXIndex(address), "ROL"),
        0x3F => (AbsoluteXIndex(address), "RLA"),
        0x40 => (Implied, "RTI"),
        0x41 => (ZeroPageXIndexIndirect(address), "EOR"),
        0x42 => (Implied, "JAM"),
        0x43 => (ZeroPageXIndexIndirect(address), "SRE"),
        0x44 => (ZeroPage(address), "NOP"),
        0x45 => (ZeroPage(address), "EOR"),
        0x46 => (ZeroPage(address), "LSR"),
        0x47 => (ZeroPage(address), "SRE"),
        0x48 => (Implied, "PHA"),
        0x49 => (Immediate(address), "EOR"),
        0x4A => (Accumulator, "LSR"),
        0x4B => (Immediate(address), "ASR"),
        0x4C => (Absolute(address), "JMP"),
        0x4D => (Absolute(address), "EOR"),
        0x4E => (Absolute(address), "LSR"),
        0x4F => (Absolute(address), "SRE"),
        0x50 => (Relative(address), "BVC"),
        0x51 => (ZeroPageYIndexIndirect(address), "EOR"),
        0x52 => (Implied, "JAM"),
        0x53 => (ZeroPageYIndexIndirect(address), "SRE"),
        0x54 => (ZeroPageXIndex(address), "NOP"),
        0x55 => (ZeroPageXIndex(address), "EOR"),
        0x56 => (ZeroPageXIndex(address), "LSR"),
        0x57 => (ZeroPageXIndex(address), "SRE"),
        0x58 => (Implied, "CLI"),
        0x59 => (AbsoluteYIndex(address), "EOR"),
        0x5A => (Implied, "NOP"),
        0x5B => (AbsoluteYIndex(address), "SRE"),
        0x5C => (AbsoluteXIndex(address), "NOP"),
        0x5D => (AbsoluteXIndex(address), "EOR"),
        0x5E => (AbsoluteXIndex(address), "LSR"),
        0x5F => (AbsoluteXIndex(address), "SRE"),
        0x60 => (Implied, "RTS"),
        0x61 => (ZeroPageXIndexIndirect(address), "ADC"),
        0x62 => (Implied, "JAM"),
        0x63 => (ZeroPageXIndexIndirect(address), "RRA"),
        0x64 => (ZeroPage(address), "NOP"),
        0x65 => (ZeroPage(address), "ADC"),
        0x66 => (ZeroPage(address), "ROR"),
        0x67 => (ZeroPage(address), "RRA"),
        0x68 => (Implied, "PLA"),
        0x69 => (Immediate(address), "ADC"),
        0x6A => (Accumulator, "ROR"),
        0x6B => (Immediate(address), "ARR"),
        0x6C => (AbsoluteIndirect(address), "JMP"),
        0x6D => (Absolute(address), "ADC"),
        0x6E => (Absolute(address), "ROR"),
        0x6F => (Absolute(address), "RRA"),
        0x70 => (Relative(address), "BVS"),
        0x71 => (ZeroPageYIndexIndirect(address), "ADC"),
        0x72 => (Implied, "JAM"),
        0x73 => (ZeroPageYIndexIndirect(address), "RRA"),
        0x74 => (ZeroPageXIndex(address), "NOP"),
        0x75 => (ZeroPageXIndex(address), "ADC"),
        0x76 => (ZeroPageXIndex(address), "ROR"),
        0x77 => (ZeroPageXIndex(address), "RRA"),
        0x78 => (Implied, "SEI"),
        0x79 => (AbsoluteYIndex(address), "ADC"),
        0x7A => (Implied, "NOP"),
        0x7B => (AbsoluteYIndex(address), "RRA"),
        0x7C => (AbsoluteXIndex(address), "NOP"),
        0x7D => (AbsoluteXIndex(address), "ADC"),
        0x7E => (AbsoluteXIndex(address), "ROR"),
        0x7F => (AbsoluteXIndex(address), "RRA"),
        0x80 => (Immediate(address), "NOP"),
        0x81 => (ZeroPageXIndexIndirect(address), "STA"),
        0x82 => (Immediate(address), "NOP"),
        0x83 => (ZeroPageXIndexIndirect(address), "SAX"),
        0x84 => (ZeroPage(address), "STY"),
        0x85 => (ZeroPage(address), "STA"),
        0x86 => (ZeroPage(address), "STX"),
        0x87 => (ZeroPage(address), "SAX"),
        0x88 => (Implied, "DEY"),
        0x89 => (Immediate(address), "NOP"),
        0x8A => (Implied, "TXA"),
        0x8B => (Immediate(address), "XAA"),
        0x8C => (Absolute(address), "STY"),
        0x8D => (Absolute(address), "STA"),
        0x8E => (Absolute(address), "STX"),
        0x8F => (Absolute(address), "SAX"),
        0x90 => (Relative(address), "BCC"),
        0x91 => (ZeroPageYIndexIndirect(address), "STA"),
        0x92 => (Implied, "JAM"),
        0x93 => (ZeroPageYIndexIndirect(address), "SHA"),
        0x94 => (ZeroPageXIndex(address), "STY"),
        0x95 => (ZeroPageXIndex(address), "STA"),
        0x96 => (ZeroPageYIndex(address), "STX"),
        0x97 => (ZeroPageYIndex(address), "SAX"),
        0x98 => (Implied, "TYA"),
        0x99 => (AbsoluteYIndex(address), "STA"),
        0x9A => (Implied, "TXS"),
        0x9B => (AbsoluteYIndex(address), "SHS"),
        0x9C => (AbsoluteXIndex(address), "SHY"),
        0x9D => (AbsoluteXIndex(address), "STA"),
        0x9E => (AbsoluteYIndex(address), "SHX"),
        0x9F => (AbsoluteYIndex(address), "SHA"),
        0xA0 => (Immediate(address), "LDY"),
        0xA1 => (ZeroPageXIndexIndirect(address), "LDA"),
        0xA2 => (Immediate(address), "LDX"),
        0xA3 => (ZeroPageXIndexIndirect(address), "LAX"),
        0xA4 => (ZeroPage(address), "LDY"),
        0xA5 => (ZeroPage(address), "LDA"),
        0xA6 => (ZeroPage(address), "LDX"),
        0xA7 => (ZeroPage(address), "LAX"),
        0xA8 => (Implied, "TAY"),
        0xA9 => (Immediate(address), "LDA"),
        0xAA => (Implied, "TAX"),
        0xAB => (Immediate(address), "LAX"),
        0xAC => (Absolute(address), "LDY"),
        0xAD => (Absolute(address), "LDA"),
        0xAE => (Absolute(address), "LDX"),
        0xAF => (Absolute(address), "LAX"),
        0xB0 => (Relative(address), "BCS"),
        0xB1 => (ZeroPageYIndexIndirect(address), "LDA"),
        0xB2 => (Implied, "JAM"),
        0xB3 => (ZeroPageYIndexIndirect(address), "LAX"),
        0xB4 => (ZeroPageXIndex(address), "LDY"),
        0xB5 => (ZeroPageXIndex(address), "LDA"),
        0xB6 => (ZeroPageYIndex(address), "LDX"),
        0xB7 => (ZeroPageYIndex(address), "LAX"),
        0xB8 => (Implied, "CLV"),
        0xB9 => (AbsoluteYIndex(address), "LDA"),
        0xBA => (Implied, "TSX"),
        0xBB => (AbsoluteYIndex(address), "LAS"),
        0xBC => (AbsoluteXIndex(address), "LDY"),
        0xBD => (AbsoluteXIndex(address), "LDA"),
        0xBE => (AbsoluteYIndex(address), "LDX"),
        0xBF => (AbsoluteYIndex(address), "LAX"),
        0xC0 => (Immediate(address), "CPY"),
        0xC1 => (ZeroPageXIndexIndirect(address), "CMP"),
        0xC2 => (Immediate(address), "NOP"),
        0xC3 => (ZeroPageXIndexIndirect(address), "DCP"),
        0xC4 => (ZeroPage(address), "CPY"),
        0xC5 => (ZeroPage(address), "CMP"),
        0xC6 => (ZeroPage(address), "DEC"),
        0xC7 => (ZeroPage(address), "DCP"),
        0xC8 => (Implied, "INY"),
        0xC9 => (Immediate(address), "CMP"),
        0xCA => (Implied, "DEX"),
        0xCB => (Immediate(address), "SBX"),
        0xCC => (Absolute(address), "CPY"),
        0xCD => (Absolute(address), "CMP"),
        0xCE => (Absolute(address), "DEC"),
        0xCF => (Absolute(address), "DCP"),
        0xD0 => (Relative(address), "BNE"),
        0xD1 => (ZeroPageYIndexIndirect(address), "CMP"),
        0xD2 => (Implied, "JAM"),
        0xD3 => (ZeroPageYIndexIndirect(address), "DCP"),
        0xD4 => (ZeroPageXIndex(address), "NOP"),
        0xD5 => (ZeroPageXIndex(address), "CMP"),
        0xD6 => (ZeroPageXIndex(address), "DEC"),
        0xD7 => (ZeroPageXIndex(address), "DCP"),
        0xD8 => (Implied, "CLD"),
        0xD9 => (AbsoluteYIndex(address), "CMP"),
        0xDA => (Implied, "NOP"),
        0xDB => (AbsoluteYIndex(address), "DCP"),
        0xDC => (AbsoluteXIndex(address), "NOP"),
        0xDD => (AbsoluteXIndex(address), "CMP"),
        0xDE => (AbsoluteXIndex(address), "DEC"),
        0xDF => (AbsoluteXIndex(address), "DCP"),
        0xE0 => (Immediate(address), "CPX"),
        0xE1 => (ZeroPageXIndexIndirect(address), "SBC"),
        0xE2 => (Immediate(address), "NOP"),
        0xE3 => (ZeroPageXIndexIndirect(address), "ISC"),
        0xE4 => (ZeroPage(address), "CPX"),
        0xE5 => (ZeroPage(address), "SBC"),
        0xE6 => (ZeroPage(address), "INC"),
        0xE7 => (ZeroPage(address), "ISC"),
        0xE8 => (Implied, "INX"),
        0xE9 => (Immediate(address), "SBC"),
        0xEA => (Implied, "NOP"),
        0xEB => (Immediate(address), "SBC"),
        0xEC => (Absolute(address), "CPX"),
        0xED => (Absolute(address), "SBC"),
        0xEE => (Absolute(address), "INC"),
        0xEF => (Absolute(address), "ISC"),
        0xF0 => (Relative(address), "BEQ"),
        0xF1 => (ZeroPageYIndexIndirect(address), "SBC"),
        0xF2 => (Implied, "JAM"),
        0xF3 => (ZeroPageYIndexIndirect(address), "ISC"),
        0xF4 => (ZeroPageXIndex(address), "NOP"),
        0xF5 => (ZeroPageXIndex(address), "SBC"),
        0xF6 => (ZeroPageXIndex(address), "INC"),
        0xF7 => (ZeroPageXIndex(address), "ISC"),
        0xF8 => (Implied, "SED"),
        0xF9 => (AbsoluteYIndex(address), "SBC"),
        0xFA => (Implied, "NOP"),
        0xFB => (AbsoluteYIndex(address), "ISC"),
        0xFC => (AbsoluteXIndex(address), "NOP"),
        0xFD => (AbsoluteXIndex(address), "SBC"),
        0xFE => (AbsoluteXIndex(address), "INC"),
        0xFF => (AbsoluteXIndex(address), "ISC"),
    }
}
