use AddressingMode::{
    Absolute, AbsoluteIndirect, AbsoluteXIndex, AbsoluteYIndex, Accumulator, Immediate, Implied,
    Relative, ZeroPage, ZeroPageXIndex, ZeroPageXIndexIndirect, ZeroPageYIndex,
    ZeroPageYIndexIndirect,
};

use crate::cpu::addressing_mode::AddressingMode;
use crate::cpu::instructions;
use crate::cpu::registers::Registers;
use crate::memory::Memory;

type InstructionFunction = fn(&mut Memory, &mut Registers, Operation);

pub struct Operation {
    pub addressing_mode: AddressingMode,
    pub instruction_function: InstructionFunction,
}

impl Operation {
    pub fn next(registers: &mut Registers, memory: &Memory) -> Operation {
        let opcode = memory.read_byte(registers.program_counter);

        let (mut addressing_mode, instruction_function) =
            resolve_opcode(opcode, registers.program_counter + 1);

        addressing_mode = addressing_mode.process(registers, memory);

        registers.increment_program_counter(&addressing_mode);

        Operation {
            addressing_mode,
            instruction_function,
        }
    }
}

// EXHAUSTIVE list of opcodes
fn resolve_opcode(opcode: u8, address: usize) -> (AddressingMode, InstructionFunction) {
    match opcode {
        0x00 => (Implied, instructions::brk),
        0x01 => (ZeroPageXIndexIndirect(address), instructions::ora),
        0x02 => (Implied, instructions::jam),
        0x03 => (ZeroPageXIndexIndirect(address), instructions::slo),
        0x04 => (ZeroPage(address), instructions::nop),
        0x05 => (ZeroPage(address), instructions::ora),
        0x06 => (ZeroPage(address), instructions::asl),
        0x07 => (ZeroPage(address), instructions::slo),
        0x08 => (Implied, instructions::php),
        0x09 => (Immediate(address), instructions::ora),
        0x0A => (Accumulator, instructions::asl),
        0x0B => (Immediate(address), instructions::anc),
        0x0C => (Absolute(address), instructions::nop),
        0x0D => (Absolute(address), instructions::ora),
        0x0E => (Absolute(address), instructions::asl),
        0x0F => (Absolute(address), instructions::slo),
        0x10 => (Relative(address), instructions::bpl),
        0x11 => (ZeroPageYIndexIndirect(address), instructions::ora),
        0x12 => (Implied, instructions::jam),
        0x13 => (ZeroPageYIndexIndirect(address), instructions::slo),
        0x14 => (ZeroPageXIndex(address), instructions::nop),
        0x15 => (ZeroPageXIndex(address), instructions::ora),
        0x16 => (ZeroPageXIndex(address), instructions::asl),
        0x17 => (ZeroPageXIndex(address), instructions::slo),
        0x18 => (Implied, instructions::clc),
        0x19 => (AbsoluteYIndex(address), instructions::ora),
        0x1A => (Implied, instructions::nop),
        0x1B => (AbsoluteYIndex(address), instructions::slo),
        0x1C => (AbsoluteXIndex(address), instructions::nop),
        0x1D => (AbsoluteXIndex(address), instructions::ora),
        0x1E => (AbsoluteXIndex(address), instructions::asl),
        0x1F => (AbsoluteXIndex(address), instructions::slo),
        0x20 => (Absolute(address), instructions::jsr),
        0x21 => (ZeroPageXIndexIndirect(address), instructions::and),
        0x22 => (Implied, instructions::jam),
        0x23 => (ZeroPageXIndexIndirect(address), instructions::rla),
        0x24 => (ZeroPage(address), instructions::bit),
        0x25 => (ZeroPage(address), instructions::and),
        0x26 => (ZeroPage(address), instructions::rol),
        0x27 => (ZeroPage(address), instructions::rla),
        0x28 => (Implied, instructions::plp),
        0x29 => (Immediate(address), instructions::and),
        0x2A => (Accumulator, instructions::rol),
        0x2B => (Immediate(address), instructions::anc),
        0x2C => (Absolute(address), instructions::bit),
        0x2D => (Absolute(address), instructions::and),
        0x2E => (Absolute(address), instructions::rol),
        0x2F => (Absolute(address), instructions::rla),
        0x30 => (Relative(address), instructions::bmi),
        0x31 => (ZeroPageYIndexIndirect(address), instructions::and),
        0x32 => (Implied, instructions::jam),
        0x33 => (ZeroPageYIndexIndirect(address), instructions::rla),
        0x34 => (ZeroPageXIndex(address), instructions::nop),
        0x35 => (ZeroPageXIndex(address), instructions::and),
        0x36 => (ZeroPageXIndex(address), instructions::rol),
        0x37 => (ZeroPageXIndex(address), instructions::rla),
        0x38 => (Implied, instructions::sec),
        0x39 => (AbsoluteYIndex(address), instructions::and),
        0x3A => (Implied, instructions::nop),
        0x3B => (AbsoluteYIndex(address), instructions::rla),
        0x3C => (AbsoluteXIndex(address), instructions::nop),
        0x3D => (AbsoluteXIndex(address), instructions::and),
        0x3E => (AbsoluteXIndex(address), instructions::rol),
        0x3F => (AbsoluteXIndex(address), instructions::rla),
        0x40 => (Implied, instructions::rti),
        0x41 => (ZeroPageXIndexIndirect(address), instructions::eor),
        0x42 => (Implied, instructions::jam),
        0x43 => (ZeroPageXIndexIndirect(address), instructions::sre),
        0x44 => (ZeroPage(address), instructions::nop),
        0x45 => (ZeroPage(address), instructions::eor),
        0x46 => (ZeroPage(address), instructions::lsr),
        0x47 => (ZeroPage(address), instructions::sre),
        0x48 => (Implied, instructions::pha),
        0x49 => (Immediate(address), instructions::eor),
        0x4A => (Accumulator, instructions::lsr),
        0x4B => (Immediate(address), instructions::asr),
        0x4C => (Absolute(address), instructions::jmp),
        0x4D => (Absolute(address), instructions::eor),
        0x4E => (Absolute(address), instructions::lsr),
        0x4F => (Absolute(address), instructions::sre),
        0x50 => (Relative(address), instructions::bvc),
        0x51 => (ZeroPageYIndexIndirect(address), instructions::eor),
        0x52 => (Implied, instructions::jam),
        0x53 => (ZeroPageYIndexIndirect(address), instructions::sre),
        0x54 => (ZeroPageXIndex(address), instructions::nop),
        0x55 => (ZeroPageXIndex(address), instructions::eor),
        0x56 => (ZeroPageXIndex(address), instructions::lsr),
        0x57 => (ZeroPageXIndex(address), instructions::sre),
        0x58 => (Implied, instructions::cli),
        0x59 => (AbsoluteYIndex(address), instructions::eor),
        0x5A => (Implied, instructions::nop),
        0x5B => (AbsoluteYIndex(address), instructions::sre),
        0x5C => (AbsoluteXIndex(address), instructions::nop),
        0x5D => (AbsoluteXIndex(address), instructions::eor),
        0x5E => (AbsoluteXIndex(address), instructions::lsr),
        0x5F => (AbsoluteXIndex(address), instructions::sre),
        0x60 => (Implied, instructions::rts),
        0x61 => (ZeroPageXIndexIndirect(address), instructions::adc),
        0x62 => (Implied, instructions::jam),
        0x63 => (ZeroPageXIndexIndirect(address), instructions::rra),
        0x64 => (ZeroPage(address), instructions::nop),
        0x65 => (ZeroPage(address), instructions::adc),
        0x66 => (ZeroPage(address), instructions::ror),
        0x67 => (ZeroPage(address), instructions::rra),
        0x68 => (Implied, instructions::pla),
        0x69 => (Immediate(address), instructions::adc),
        0x6A => (Accumulator, instructions::ror),
        0x6B => (Immediate(address), instructions::arr),
        0x6C => (AbsoluteIndirect(address), instructions::jmp),
        0x6D => (Absolute(address), instructions::adc),
        0x6E => (Absolute(address), instructions::ror),
        0x6F => (Absolute(address), instructions::rra),
        0x70 => (Relative(address), instructions::bvs),
        0x71 => (ZeroPageYIndexIndirect(address), instructions::adc),
        0x72 => (Implied, instructions::jam),
        0x73 => (ZeroPageYIndexIndirect(address), instructions::rra),
        0x74 => (ZeroPageXIndex(address), instructions::nop),
        0x75 => (ZeroPageXIndex(address), instructions::adc),
        0x76 => (ZeroPageXIndex(address), instructions::ror),
        0x77 => (ZeroPageXIndex(address), instructions::rra),
        0x78 => (Implied, instructions::sei),
        0x79 => (AbsoluteYIndex(address), instructions::adc),
        0x7A => (Implied, instructions::nop),
        0x7B => (AbsoluteYIndex(address), instructions::rra),
        0x7C => (AbsoluteXIndex(address), instructions::nop),
        0x7D => (AbsoluteXIndex(address), instructions::adc),
        0x7E => (AbsoluteXIndex(address), instructions::ror),
        0x7F => (AbsoluteXIndex(address), instructions::rra),
        0x80 => (Immediate(address), instructions::nop),
        0x81 => (ZeroPageXIndexIndirect(address), instructions::sta),
        0x82 => (Immediate(address), instructions::nop),
        0x83 => (ZeroPageXIndexIndirect(address), instructions::sax),
        0x84 => (ZeroPage(address), instructions::sty),
        0x85 => (ZeroPage(address), instructions::sta),
        0x86 => (ZeroPage(address), instructions::stx),
        0x87 => (ZeroPage(address), instructions::sax),
        0x88 => (Implied, instructions::dey),
        0x89 => (Immediate(address), instructions::nop),
        0x8A => (Implied, instructions::txa),
        0x8B => (Immediate(address), instructions::xaa),
        0x8C => (Absolute(address), instructions::sty),
        0x8D => (Absolute(address), instructions::sta),
        0x8E => (Absolute(address), instructions::stx),
        0x8F => (Absolute(address), instructions::sax),
        0x90 => (Relative(address), instructions::bcc),
        0x91 => (ZeroPageYIndexIndirect(address), instructions::sta),
        0x92 => (Implied, instructions::jam),
        0x93 => (ZeroPageYIndexIndirect(address), instructions::sha),
        0x94 => (ZeroPageXIndex(address), instructions::sty),
        0x95 => (ZeroPageXIndex(address), instructions::sta),
        0x96 => (ZeroPageYIndex(address), instructions::stx),
        0x97 => (ZeroPageYIndex(address), instructions::sax),
        0x98 => (Implied, instructions::tya),
        0x99 => (AbsoluteYIndex(address), instructions::sta),
        0x9A => (Implied, instructions::txs),
        0x9B => (AbsoluteYIndex(address), instructions::shs),
        0x9C => (AbsoluteXIndex(address), instructions::shy),
        0x9D => (AbsoluteXIndex(address), instructions::sta),
        0x9E => (AbsoluteYIndex(address), instructions::shx),
        0x9F => (AbsoluteYIndex(address), instructions::sha),
        0xA0 => (Immediate(address), instructions::ldy),
        0xA1 => (ZeroPageXIndexIndirect(address), instructions::lda),
        0xA2 => (Immediate(address), instructions::ldx),
        0xA3 => (ZeroPageXIndexIndirect(address), instructions::lax),
        0xA4 => (ZeroPage(address), instructions::ldy),
        0xA5 => (ZeroPage(address), instructions::lda),
        0xA6 => (ZeroPage(address), instructions::ldx),
        0xA7 => (ZeroPage(address), instructions::lax),
        0xA8 => (Implied, instructions::tay),
        0xA9 => (Immediate(address), instructions::lda),
        0xAA => (Implied, instructions::tax),
        0xAB => (Immediate(address), instructions::lax),
        0xAC => (Absolute(address), instructions::ldy),
        0xAD => (Absolute(address), instructions::lda),
        0xAE => (Absolute(address), instructions::ldx),
        0xAF => (Absolute(address), instructions::lax),
        0xB0 => (Relative(address), instructions::bcs),
        0xB1 => (ZeroPageYIndexIndirect(address), instructions::lda),
        0xB2 => (Implied, instructions::jam),
        0xB3 => (ZeroPageYIndexIndirect(address), instructions::lax),
        0xB4 => (ZeroPageXIndex(address), instructions::ldy),
        0xB5 => (ZeroPageXIndex(address), instructions::lda),
        0xB6 => (ZeroPageYIndex(address), instructions::ldx),
        0xB7 => (ZeroPageYIndex(address), instructions::lax),
        0xB8 => (Implied, instructions::clv),
        0xB9 => (AbsoluteYIndex(address), instructions::lda),
        0xBA => (Implied, instructions::tsx),
        0xBB => (AbsoluteYIndex(address), instructions::las),
        0xBC => (AbsoluteXIndex(address), instructions::ldy),
        0xBD => (AbsoluteXIndex(address), instructions::lda),
        0xBE => (AbsoluteYIndex(address), instructions::ldx),
        0xBF => (AbsoluteYIndex(address), instructions::lax),
        0xC0 => (Immediate(address), instructions::cpy),
        0xC1 => (ZeroPageXIndexIndirect(address), instructions::cmp),
        0xC2 => (Immediate(address), instructions::nop),
        0xC3 => (ZeroPageXIndexIndirect(address), instructions::dcp),
        0xC4 => (ZeroPage(address), instructions::cpy),
        0xC5 => (ZeroPage(address), instructions::cmp),
        0xC6 => (ZeroPage(address), instructions::dec),
        0xC7 => (ZeroPage(address), instructions::dcp),
        0xC8 => (Implied, instructions::iny),
        0xC9 => (Immediate(address), instructions::cmp),
        0xCA => (Implied, instructions::dex),
        0xCB => (Immediate(address), instructions::sbx),
        0xCC => (Absolute(address), instructions::cpy),
        0xCD => (Absolute(address), instructions::cmp),
        0xCE => (Absolute(address), instructions::dec),
        0xCF => (Absolute(address), instructions::dcp),
        0xD0 => (Relative(address), instructions::bne),
        0xD1 => (ZeroPageYIndexIndirect(address), instructions::cmp),
        0xD2 => (Implied, instructions::jam),
        0xD3 => (ZeroPageYIndexIndirect(address), instructions::dcp),
        0xD4 => (ZeroPageXIndex(address), instructions::nop),
        0xD5 => (ZeroPageXIndex(address), instructions::cmp),
        0xD6 => (ZeroPageXIndex(address), instructions::dec),
        0xD7 => (ZeroPageXIndex(address), instructions::dcp),
        0xD8 => (Implied, instructions::cld),
        0xD9 => (AbsoluteYIndex(address), instructions::cmp),
        0xDA => (Implied, instructions::nop),
        0xDB => (AbsoluteYIndex(address), instructions::dcp),
        0xDC => (AbsoluteXIndex(address), instructions::nop),
        0xDD => (AbsoluteXIndex(address), instructions::cmp),
        0xDE => (AbsoluteXIndex(address), instructions::dec),
        0xDF => (AbsoluteXIndex(address), instructions::dcp),
        0xE0 => (Immediate(address), instructions::cpx),
        0xE1 => (ZeroPageXIndexIndirect(address), instructions::sbc),
        0xE2 => (Immediate(address), instructions::nop),
        0xE3 => (ZeroPageXIndexIndirect(address), instructions::isc),
        0xE4 => (ZeroPage(address), instructions::cpx),
        0xE5 => (ZeroPage(address), instructions::sbc),
        0xE6 => (ZeroPage(address), instructions::inc),
        0xE7 => (ZeroPage(address), instructions::isc),
        0xE8 => (Implied, instructions::inx),
        0xE9 => (Immediate(address), instructions::sbc),
        0xEA => (Implied, instructions::nop),
        0xEB => (Immediate(address), instructions::sbc),
        0xEC => (Absolute(address), instructions::cpx),
        0xED => (Absolute(address), instructions::sbc),
        0xEE => (Absolute(address), instructions::inc),
        0xEF => (Absolute(address), instructions::isc),
        0xF0 => (Relative(address), instructions::beq),
        0xF1 => (ZeroPageYIndexIndirect(address), instructions::sbc),
        0xF2 => (Implied, instructions::jam),
        0xF3 => (ZeroPageYIndexIndirect(address), instructions::isc),
        0xF4 => (ZeroPageXIndex(address), instructions::nop),
        0xF5 => (ZeroPageXIndex(address), instructions::sbc),
        0xF6 => (ZeroPageXIndex(address), instructions::inc),
        0xF7 => (ZeroPageXIndex(address), instructions::isc),
        0xF8 => (Implied, instructions::sed),
        0xF9 => (AbsoluteYIndex(address), instructions::sbc),
        0xFA => (Implied, instructions::nop),
        0xFB => (AbsoluteYIndex(address), instructions::isc),
        0xFC => (AbsoluteXIndex(address), instructions::nop),
        0xFD => (AbsoluteXIndex(address), instructions::sbc),
        0xFE => (AbsoluteXIndex(address), instructions::inc),
        0xFF => (AbsoluteXIndex(address), instructions::isc),
    }
}
