use AddressingMode::{
    Absolute, AbsoluteIndirect, AbsoluteXIndex, AbsoluteYIndex, Accumulator, Immediate, Implied,
    Relative, ZeroPage, ZeroPageXIndex, ZeroPageXIndexIndirect, ZeroPageYIndex,
    ZeroPageYIndexIndirect,
};

use crate::cpu::addressing_mode::AddressingMode;
use crate::cpu::instructions;
use crate::cpu::registers::Registers;
use crate::memory::Memory;

type InstructionFunction = fn(&mut Memory, &mut Registers, Operation);

pub struct Operation {
    pub addressing_mode: AddressingMode,
    pub instruction_function: InstructionFunction,
    pub cycles: u8,
}

impl Operation {
    pub fn next(registers: &mut Registers, memory: &Memory) -> Operation {
        let opcode = memory.read_byte(registers.program_counter);

        let (addressing_mode, instruction_function, mut cycles) =
            resolve_opcode(opcode, registers.program_counter + 1);

        let (addressing_mode, additional_cycles) = addressing_mode.process(registers, memory);

        cycles += additional_cycles;

        registers.increment_program_counter(&addressing_mode);

        Operation {
            addressing_mode,
            instruction_function,
            cycles,
        }
    }
}

// EXHAUSTIVE list of opcodes
fn resolve_opcode(opcode: u8, address: usize) -> (AddressingMode, InstructionFunction, u8) {
    match opcode {
        0x00 => (Implied, instructions::brk, 7),
        0x01 => (ZeroPageXIndexIndirect(address), instructions::ora, 6),
        0x02 => (Implied, instructions::jam, 0),
        0x03 => (ZeroPageXIndexIndirect(address), instructions::slo, 8),
        0x04 => (ZeroPage(address), instructions::nop, 3),
        0x05 => (ZeroPage(address), instructions::ora, 3),
        0x06 => (ZeroPage(address), instructions::asl, 5),
        0x07 => (ZeroPage(address), instructions::slo, 5),
        0x08 => (Implied, instructions::php, 3),
        0x09 => (Immediate(address), instructions::ora, 2),
        0x0A => (Accumulator, instructions::asl, 2),
        0x0B => (Immediate(address), instructions::anc, 2),
        0x0C => (Absolute(address), instructions::nop, 4),
        0x0D => (Absolute(address), instructions::ora, 4),
        0x0E => (Absolute(address), instructions::asl, 6),
        0x0F => (Absolute(address), instructions::slo, 6),
        0x10 => (Relative(address), instructions::bpl, 2),
        0x11 => (ZeroPageYIndexIndirect(address), instructions::ora, 5),
        0x12 => (Implied, instructions::jam, 0),
        0x13 => (ZeroPageYIndexIndirect(address), instructions::slo, 8),
        0x14 => (ZeroPageXIndex(address), instructions::nop, 4),
        0x15 => (ZeroPageXIndex(address), instructions::ora, 4),
        0x16 => (ZeroPageXIndex(address), instructions::asl, 6),
        0x17 => (ZeroPageXIndex(address), instructions::slo, 6),
        0x18 => (Implied, instructions::clc, 2),
        0x19 => (AbsoluteYIndex(address), instructions::ora, 4),
        0x1A => (Implied, instructions::nop, 2),
        0x1B => (AbsoluteYIndex(address), instructions::slo, 7),
        0x1C => (AbsoluteXIndex(address), instructions::nop, 4),
        0x1D => (AbsoluteXIndex(address), instructions::ora, 4),
        0x1E => (AbsoluteXIndex(address), instructions::asl, 7),
        0x1F => (AbsoluteXIndex(address), instructions::slo, 7),
        0x20 => (Absolute(address), instructions::jsr, 6),
        0x21 => (ZeroPageXIndexIndirect(address), instructions::and, 6),
        0x22 => (Implied, instructions::jam, 0),
        0x23 => (ZeroPageXIndexIndirect(address), instructions::rla, 8),
        0x24 => (ZeroPage(address), instructions::bit, 3),
        0x25 => (ZeroPage(address), instructions::and, 3),
        0x26 => (ZeroPage(address), instructions::rol, 5),
        0x27 => (ZeroPage(address), instructions::rla, 5),
        0x28 => (Implied, instructions::plp, 4),
        0x29 => (Immediate(address), instructions::and, 2),
        0x2A => (Accumulator, instructions::rol, 2),
        0x2B => (Immediate(address), instructions::anc, 2),
        0x2C => (Absolute(address), instructions::bit, 4),
        0x2D => (Absolute(address), instructions::and, 4),
        0x2E => (Absolute(address), instructions::rol, 6),
        0x2F => (Absolute(address), instructions::rla, 6),
        0x30 => (Relative(address), instructions::bmi, 2),
        0x31 => (ZeroPageYIndexIndirect(address), instructions::and, 5),
        0x32 => (Implied, instructions::jam, 0),
        0x33 => (ZeroPageYIndexIndirect(address), instructions::rla, 8),
        0x34 => (ZeroPageXIndex(address), instructions::nop, 4),
        0x35 => (ZeroPageXIndex(address), instructions::and, 4),
        0x36 => (ZeroPageXIndex(address), instructions::rol, 6),
        0x37 => (ZeroPageXIndex(address), instructions::rla, 6),
        0x38 => (Implied, instructions::sec, 2),
        0x39 => (AbsoluteYIndex(address), instructions::and, 4),
        0x3A => (Implied, instructions::nop, 2),
        0x3B => (AbsoluteYIndex(address), instructions::rla, 7),
        0x3C => (AbsoluteXIndex(address), instructions::nop, 4),
        0x3D => (AbsoluteXIndex(address), instructions::and, 4),
        0x3E => (AbsoluteXIndex(address), instructions::rol, 7),
        0x3F => (AbsoluteXIndex(address), instructions::rla, 7),
        0x40 => (Implied, instructions::rti, 6),
        0x41 => (ZeroPageXIndexIndirect(address), instructions::eor, 6),
        0x42 => (Implied, instructions::jam, 0),
        0x43 => (ZeroPageXIndexIndirect(address), instructions::sre, 8),
        0x44 => (ZeroPage(address), instructions::nop, 3),
        0x45 => (ZeroPage(address), instructions::eor, 3),
        0x46 => (ZeroPage(address), instructions::lsr, 5),
        0x47 => (ZeroPage(address), instructions::sre, 5),
        0x48 => (Implied, instructions::pha, 3),
        0x49 => (Immediate(address), instructions::eor, 2),
        0x4A => (Accumulator, instructions::lsr, 2),
        0x4B => (Immediate(address), instructions::asr, 2),
        0x4C => (Absolute(address), instructions::jmp, 3),
        0x4D => (Absolute(address), instructions::eor, 4),
        0x4E => (Absolute(address), instructions::lsr, 6),
        0x4F => (Absolute(address), instructions::sre, 6),
        0x50 => (Relative(address), instructions::bvc, 2),
        0x51 => (ZeroPageYIndexIndirect(address), instructions::eor, 5),
        0x52 => (Implied, instructions::jam, 0),
        0x53 => (ZeroPageYIndexIndirect(address), instructions::sre, 8),
        0x54 => (ZeroPageXIndex(address), instructions::nop, 4),
        0x55 => (ZeroPageXIndex(address), instructions::eor, 4),
        0x56 => (ZeroPageXIndex(address), instructions::lsr, 6),
        0x57 => (ZeroPageXIndex(address), instructions::sre, 6),
        0x58 => (Implied, instructions::cli, 2),
        0x59 => (AbsoluteYIndex(address), instructions::eor, 4),
        0x5A => (Implied, instructions::nop, 2),
        0x5B => (AbsoluteYIndex(address), instructions::sre, 7),
        0x5C => (AbsoluteXIndex(address), instructions::nop, 4),
        0x5D => (AbsoluteXIndex(address), instructions::eor, 4),
        0x5E => (AbsoluteXIndex(address), instructions::lsr, 7),
        0x5F => (AbsoluteXIndex(address), instructions::sre, 7),
        0x60 => (Implied, instructions::rts, 6),
        0x61 => (ZeroPageXIndexIndirect(address), instructions::adc, 6),
        0x62 => (Implied, instructions::jam, 0),
        0x63 => (ZeroPageXIndexIndirect(address), instructions::rra, 8),
        0x64 => (ZeroPage(address), instructions::nop, 3),
        0x65 => (ZeroPage(address), instructions::adc, 3),
        0x66 => (ZeroPage(address), instructions::ror, 5),
        0x67 => (ZeroPage(address), instructions::rra, 5),
        0x68 => (Implied, instructions::pla, 4),
        0x69 => (Immediate(address), instructions::adc, 2),
        0x6A => (Accumulator, instructions::ror, 2),
        0x6B => (Immediate(address), instructions::arr, 2),
        0x6C => (AbsoluteIndirect(address), instructions::jmp, 5),
        0x6D => (Absolute(address), instructions::adc, 4),
        0x6E => (Absolute(address), instructions::ror, 6),
        0x6F => (Absolute(address), instructions::rra, 6),
        0x70 => (Relative(address), instructions::bvs, 2),
        0x71 => (ZeroPageYIndexIndirect(address), instructions::adc, 5),
        0x72 => (Implied, instructions::jam, 0),
        0x73 => (ZeroPageYIndexIndirect(address), instructions::rra, 8),
        0x74 => (ZeroPageXIndex(address), instructions::nop, 4),
        0x75 => (ZeroPageXIndex(address), instructions::adc, 4),
        0x76 => (ZeroPageXIndex(address), instructions::ror, 6),
        0x77 => (ZeroPageXIndex(address), instructions::rra, 6),
        0x78 => (Implied, instructions::sei, 2),
        0x79 => (AbsoluteYIndex(address), instructions::adc, 4),
        0x7A => (Implied, instructions::nop, 2),
        0x7B => (AbsoluteYIndex(address), instructions::rra, 7),
        0x7C => (AbsoluteXIndex(address), instructions::nop, 4),
        0x7D => (AbsoluteXIndex(address), instructions::adc, 4),
        0x7E => (AbsoluteXIndex(address), instructions::ror, 7),
        0x7F => (AbsoluteXIndex(address), instructions::rra, 7),
        0x80 => (Immediate(address), instructions::nop, 2),
        0x81 => (ZeroPageXIndexIndirect(address), instructions::sta, 6),
        0x82 => (Immediate(address), instructions::nop, 2),
        0x83 => (ZeroPageXIndexIndirect(address), instructions::sax, 6),
        0x84 => (ZeroPage(address), instructions::sty, 3),
        0x85 => (ZeroPage(address), instructions::sta, 3),
        0x86 => (ZeroPage(address), instructions::stx, 3),
        0x87 => (ZeroPage(address), instructions::sax, 3),
        0x88 => (Implied, instructions::dey, 2),
        0x89 => (Immediate(address), instructions::nop, 2),
        0x8A => (Implied, instructions::txa, 2),
        0x8B => (Immediate(address), instructions::xaa, 2),
        0x8C => (Absolute(address), instructions::sty, 4),
        0x8D => (Absolute(address), instructions::sta, 4),
        0x8E => (Absolute(address), instructions::stx, 4),
        0x8F => (Absolute(address), instructions::sax, 4),
        0x90 => (Relative(address), instructions::bcc, 2),
        0x91 => (ZeroPageYIndexIndirect(address), instructions::sta, 6),
        0x92 => (Implied, instructions::jam, 0),
        0x93 => (ZeroPageYIndexIndirect(address), instructions::sha, 6),
        0x94 => (ZeroPageXIndex(address), instructions::sty, 4),
        0x95 => (ZeroPageXIndex(address), instructions::sta, 4),
        0x96 => (ZeroPageYIndex(address), instructions::stx, 4),
        0x97 => (ZeroPageYIndex(address), instructions::sax, 4),
        0x98 => (Implied, instructions::tya, 2),
        0x99 => (AbsoluteYIndex(address), instructions::sta, 5),
        0x9A => (Implied, instructions::txs, 2),
        0x9B => (AbsoluteYIndex(address), instructions::shs, 5),
        0x9C => (AbsoluteXIndex(address), instructions::shy, 5),
        0x9D => (AbsoluteXIndex(address), instructions::sta, 5),
        0x9E => (AbsoluteYIndex(address), instructions::shx, 5),
        0x9F => (AbsoluteYIndex(address), instructions::sha, 5),
        0xA0 => (Immediate(address), instructions::ldy, 2),
        0xA1 => (ZeroPageXIndexIndirect(address), instructions::lda, 6),
        0xA2 => (Immediate(address), instructions::ldx, 2),
        0xA3 => (ZeroPageXIndexIndirect(address), instructions::lax, 6),
        0xA4 => (ZeroPage(address), instructions::ldy, 3),
        0xA5 => (ZeroPage(address), instructions::lda, 3),
        0xA6 => (ZeroPage(address), instructions::ldx, 3),
        0xA7 => (ZeroPage(address), instructions::lax, 3),
        0xA8 => (Implied, instructions::tay, 2),
        0xA9 => (Immediate(address), instructions::lda, 2),
        0xAA => (Implied, instructions::tax, 2),
        0xAB => (Immediate(address), instructions::lax, 2),
        0xAC => (Absolute(address), instructions::ldy, 4),
        0xAD => (Absolute(address), instructions::lda, 4),
        0xAE => (Absolute(address), instructions::ldx, 4),
        0xAF => (Absolute(address), instructions::lax, 4),
        0xB0 => (Relative(address), instructions::bcs, 2),
        0xB1 => (ZeroPageYIndexIndirect(address), instructions::lda, 5),
        0xB2 => (Implied, instructions::jam, 0),
        0xB3 => (ZeroPageYIndexIndirect(address), instructions::lax, 5),
        0xB4 => (ZeroPageXIndex(address), instructions::ldy, 4),
        0xB5 => (ZeroPageXIndex(address), instructions::lda, 4),
        0xB6 => (ZeroPageYIndex(address), instructions::ldx, 4),
        0xB7 => (ZeroPageYIndex(address), instructions::lax, 4),
        0xB8 => (Implied, instructions::clv, 2),
        0xB9 => (AbsoluteYIndex(address), instructions::lda, 4),
        0xBA => (Implied, instructions::tsx, 2),
        0xBB => (AbsoluteYIndex(address), instructions::las, 4),
        0xBC => (AbsoluteXIndex(address), instructions::ldy, 4),
        0xBD => (AbsoluteXIndex(address), instructions::lda, 4),
        0xBE => (AbsoluteYIndex(address), instructions::ldx, 4),
        0xBF => (AbsoluteYIndex(address), instructions::lax, 4),
        0xC0 => (Immediate(address), instructions::cpy, 2),
        0xC1 => (ZeroPageXIndexIndirect(address), instructions::cmp, 6),
        0xC2 => (Immediate(address), instructions::nop, 2),
        0xC3 => (ZeroPageXIndexIndirect(address), instructions::dcp, 8),
        0xC4 => (ZeroPage(address), instructions::cpy, 3),
        0xC5 => (ZeroPage(address), instructions::cmp, 3),
        0xC6 => (ZeroPage(address), instructions::dec, 5),
        0xC7 => (ZeroPage(address), instructions::dcp, 5),
        0xC8 => (Implied, instructions::iny, 2),
        0xC9 => (Immediate(address), instructions::cmp, 2),
        0xCA => (Implied, instructions::dex, 2),
        0xCB => (Immediate(address), instructions::sbx, 2),
        0xCC => (Absolute(address), instructions::cpy, 4),
        0xCD => (Absolute(address), instructions::cmp, 4),
        0xCE => (Absolute(address), instructions::dec, 6),
        0xCF => (Absolute(address), instructions::dcp, 6),
        0xD0 => (Relative(address), instructions::bne, 2),
        0xD1 => (ZeroPageYIndexIndirect(address), instructions::cmp, 5),
        0xD2 => (Implied, instructions::jam, 0),
        0xD3 => (ZeroPageYIndexIndirect(address), instructions::dcp, 8),
        0xD4 => (ZeroPageXIndex(address), instructions::nop, 4),
        0xD5 => (ZeroPageXIndex(address), instructions::cmp, 4),
        0xD6 => (ZeroPageXIndex(address), instructions::dec, 6),
        0xD7 => (ZeroPageXIndex(address), instructions::dcp, 6),
        0xD8 => (Implied, instructions::cld, 2),
        0xD9 => (AbsoluteYIndex(address), instructions::cmp, 4),
        0xDA => (Implied, instructions::nop, 2),
        0xDB => (AbsoluteYIndex(address), instructions::dcp, 7),
        0xDC => (AbsoluteXIndex(address), instructions::nop, 4),
        0xDD => (AbsoluteXIndex(address), instructions::cmp, 4),
        0xDE => (AbsoluteXIndex(address), instructions::dec, 7),
        0xDF => (AbsoluteXIndex(address), instructions::dcp, 7),
        0xE0 => (Immediate(address), instructions::cpx, 2),
        0xE1 => (ZeroPageXIndexIndirect(address), instructions::sbc, 6),
        0xE2 => (Immediate(address), instructions::nop, 2),
        0xE3 => (ZeroPageXIndexIndirect(address), instructions::isc, 8),
        0xE4 => (ZeroPage(address), instructions::cpx, 3),
        0xE5 => (ZeroPage(address), instructions::sbc, 3),
        0xE6 => (ZeroPage(address), instructions::inc, 5),
        0xE7 => (ZeroPage(address), instructions::isc, 5),
        0xE8 => (Implied, instructions::inx, 2),
        0xE9 => (Immediate(address), instructions::sbc, 2),
        0xEA => (Implied, instructions::nop, 2),
        0xEB => (Immediate(address), instructions::sbc, 2),
        0xEC => (Absolute(address), instructions::cpx, 4),
        0xED => (Absolute(address), instructions::sbc, 4),
        0xEE => (Absolute(address), instructions::inc, 6),
        0xEF => (Absolute(address), instructions::isc, 6),
        0xF0 => (Relative(address), instructions::beq, 2),
        0xF1 => (ZeroPageYIndexIndirect(address), instructions::sbc, 5),
        0xF2 => (Implied, instructions::jam, 0),
        0xF3 => (ZeroPageYIndexIndirect(address), instructions::isc, 8),
        0xF4 => (ZeroPageXIndex(address), instructions::nop, 4),
        0xF5 => (ZeroPageXIndex(address), instructions::sbc, 4),
        0xF6 => (ZeroPageXIndex(address), instructions::inc, 6),
        0xF7 => (ZeroPageXIndex(address), instructions::isc, 6),
        0xF8 => (Implied, instructions::sed, 2),
        0xF9 => (AbsoluteYIndex(address), instructions::sbc, 4),
        0xFA => (Implied, instructions::nop, 2),
        0xFB => (AbsoluteYIndex(address), instructions::isc, 7),
        0xFC => (AbsoluteXIndex(address), instructions::nop, 4),
        0xFD => (AbsoluteXIndex(address), instructions::sbc, 4),
        0xFE => (AbsoluteXIndex(address), instructions::inc, 7),
        0xFF => (AbsoluteXIndex(address), instructions::isc, 7),
    }
}
